# version: "3.8"

# services:
#   selenium:
#     image: selenium/standalone-chrome:latest
#     container_name: selenium
#     ports:
#       - "4444:4444"
#     shm_size: 2g  # Increase shared memory to prevent crashes

#   scraper:
#     build:
#       context: .
#     depends_on:
#       - selenium
#     command: ["python", "app.py"]
